package jiaozhu.com.animalview.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import jiaozhu.com.animalview.model.FileModel;

import jiaozhu.com.animalview.dao.FileModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileModelDaoConfig;

    private final FileModelDao fileModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileModelDaoConfig = daoConfigMap.get(FileModelDao.class).clone();
        fileModelDaoConfig.initIdentityScope(type);

        fileModelDao = new FileModelDao(fileModelDaoConfig, this);

        registerDao(FileModel.class, fileModelDao);
    }
    
    public void clear() {
        fileModelDaoConfig.clearIdentityScope();
    }

    public FileModelDao getFileModelDao() {
        return fileModelDao;
    }

}
